---
- name: "First playbook"
  hosts: all
  tasks:
    - name: "First message"
      debug:
        msg: "Hello..! Welcome..! {{ inventory_hostname }}"
    - name: "Install vim"
      yum:
        name: "vim"
        state: installed
